0,SyntaxError,"unmatched ')' (4129417547.py, line 4)",0,,2024-10-08 22:02:18.928521,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3306, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/tmp/ipykernel_146/4129417547.py"", line 4', '    weird_numbers = make_array(-2, floor(12.6), 3, pow(5,ceil(5.3))))', '                                                                    ^', ""SyntaxError: unmatched ')'""]"
1,NameError,name 'third' is not defined,0,,2024-10-08 22:14:46.247734,"[('blank_a = third', 1)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_146/3142713229.py"", line 1, in <module>', '    blank_a = third', ""NameError: name 'third' is not defined""]"
2,AttributeError,'numpy.ndarray' object has no attribute 'token',0,,2024-10-08 22:24:30.493849,"[('min_of_birth_years = min(president_birth_years.token(0,15,len(president_birth_years)-1).column(""Birth Year""))', 1)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_146/2375602507.py"", line 1, in <module>', '    min_of_birth_years = min(president_birth_years.token(0,15,len(president_birth_years)-1).column(""Birth Year""))', ""AttributeError: 'numpy.ndarray' object has no attribute 'token'. Did you mean: 'take'?""]"
3,TypeError,'int' object is not iterable,0,,2024-10-08 22:26:01.190940,"[('min_of_birth_years = min(president_birth_years.item(0))', 1)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_146/463671578.py"", line 1, in <module>', '    min_of_birth_years = min(president_birth_years.item(0))', ""TypeError: 'int' object is not iterable""]"
4,AttributeError,'numpy.ndarray' object has no attribute 'products',0,,2024-10-08 22:29:14.449704,"[('products = numbers.products(157)', 2)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_146/148209164.py"", line 2, in <module>', '    products = numbers.products(157)', ""AttributeError: 'numpy.ndarray' object has no attribute 'products'""]"
5,AttributeError,'numpy.ndarray' object has no attribute 'average',0,,2024-10-08 22:37:21.975938,"[('average = waiting_times.average()', 5)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_146/2988520829.py"", line 5, in <module>', '    average = waiting_times.average()', ""AttributeError: 'numpy.ndarray' object has no attribute 'average'""]"
6,IndentationError,"unexpected indent (1915391759.py, line 6)",0,,2024-10-08 22:54:05.108760,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3306, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/tmp/ipykernel_146/1915391759.py"", line 6', '    ...', 'IndentationError: unexpected indent']"
7,TypeError,"Use Table().with_columns() to create a new table,                 not Table.with_columns()",0,,2024-10-08 22:54:16.574879,"[('fruits = Table.with_columns(', 2), (""raise TypeError('Use Table().with_columns() to create a new table, \\"", 2584)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_146/2326490216.py"", line 2, in <module>', '    fruits = Table.with_columns(', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/datascience/tables.py"", line 2584, in with_columns', ""    raise TypeError('Use Table().with_columns() to create a new table, \\"", 'TypeError: Use Table().with_columns() to create a new table,                 not Table.with_columns()']"
8,NameError,name 'inventory' is not defined,0,,2024-10-08 22:56:00.482654,"[('inventory = Table.read_table(inventory.csv)', 1)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_146/4035618664.py"", line 1, in <module>', '    inventory = Table.read_table(inventory.csv)', ""NameError: name 'inventory' is not defined""]"
9,SyntaxError,"unterminated string literal (detected at line 1) (3230654563.py, line 1)",0,,2024-10-08 22:56:16.477088,"[('return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', 86)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3306, in run_cell_async', '    code_ast = compiler.ast_parse(cell, filename=cell_name)', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/compilerop.py"", line 86, in ast_parse', '    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)', '  File ""/tmp/ipykernel_146/3230654563.py"", line 1', '    inventory = Table.read_table(\'inventory.csv"")', '                                 ^', 'SyntaxError: unterminated string literal (detected at line 1)']"
10,ValueError,"The column ""price per fruit"" is not in the table. The table contains these columns: box ID, fruit name, count sold, price per fruit ($)",0,,2024-10-08 23:00:29.313014,"[('total_revenue = np.sum(sales.column(""count sold"")*sales.column(""price per fruit""))', 1), ('raise ValueError(', 448)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_146/1377041296.py"", line 1, in <module>', '    total_revenue = np.sum(sales.column(""count sold"")*sales.column(""price per fruit""))', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/datascience/tables.py"", line 448, in column', '    raise ValueError(', 'ValueError: The column ""price per fruit"" is not in the table. The table contains these columns: box ID, fruit name, count sold, price per fruit ($)']"
