0,TypeError,unsupported operand type(s) for +: 'int' and 'str',0,,2024-10-09 13:29:16.934684,"[('8 + ""8""', 1)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_174/451511607.py"", line 1, in <module>', '    8 + ""8""', ""TypeError: unsupported operand type(s) for +: 'int' and 'str'""]"
1,IndexError,index 66 is out of bounds for axis 0 with size 66,0,,2024-10-09 13:36:07.281499,"[('population_2016 = population_amounts.item(66)', 3)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_174/4056345982.py"", line 3, in <module>', '    population_2016 = population_amounts.item(66)', 'IndexError: index 66 is out of bounds for axis 0 with size 66']"
2,NameError,name 'imdb' is not defined,0,,2024-10-09 13:47:42.473937,"[('imdb = Table.read_table(imdb.csv)', 1)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_174/1476008076.py"", line 1, in <module>', '    imdb = Table.read_table(imdb.csv)', ""NameError: name 'imdb' is not defined""]"
3,IndexError,index 0 is out of bounds for axis 0 with size 0,0,,2024-10-09 13:52:37.876257,"[('year_population_crossed_6_billion = population.where(""Population"",are.above(6*10**10)).take(0).column(""Year"")', 1), ('return self.__getitem__(all_args)', 5882)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_174/3966031053.py"", line 1, in <module>', '    year_population_crossed_6_billion = population.where(""Population"",are.above(6*10**10)).take(0).column(""Year"")', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/datascience/tables.py"", line 5882, in __call__', '    return self.__getitem__(all_args)', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/datascience/tables.py"", line 5952, in __getitem__', '    rows = self._table.rows[row_indices_or_slice]', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/datascience/tables.py"", line 5735, in __getitem__', '    return self._row(c[i] for c in self._table._columns.values())', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/datascience/tables.py"", line 5735, in <genexpr>', '    return self._row(c[i] for c in self._table._columns.values())', 'IndexError: index 0 is out of bounds for axis 0 with size 0']"
4,NameError,name 'Year' is not defined,0,,2024-10-09 13:53:45.937906,"[('year_population_crossed_6_billion = population.where(""Population"",are.above(6*10**9)).take(0).column(Year)', 1)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_174/41231727.py"", line 1, in <module>', '    year_population_crossed_6_billion = population.where(""Population"",are.above(6*10**9)).take(0).column(Year)', ""NameError: name 'Year' is not defined. Did you mean: 'years'?""]"
5,AttributeError,'Table' object has no attribute 'cloumn',0,,2024-10-09 13:57:44.081215,"[('before_2000 = imdb.where(""Year"",are.below(2000)).cloumn(""Rating"")', 1), ('raise AttributeError(msg)', 318)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_174/2658958502.py"", line 1, in <module>', '    before_2000 = imdb.where(""Year"",are.below(2000)).cloumn(""Rating"")', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/datascience/tables.py"", line 318, in __getattr__', '    raise AttributeError(msg)', ""AttributeError: 'Table' object has no attribute 'cloumn'. Did you mean: 'column'?""]"
6,TypeError,unsupported operand type(s) for %: 'Table' and 'int',0,,2024-10-09 14:03:21.363424,"[('Year_remainder=imdb%2', 1)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_174/2908626713.py"", line 1, in <module>', '    Year_remainder=imdb%2', ""TypeError: unsupported operand type(s) for %: 'Table' and 'int'""]"
7,AttributeError,module 'numpy' has no attribute 'num',0,,2024-10-09 14:06:05.597643,"[('num_even_year_movies = imdb.num_rows-np.num(Year_remainder)', 2), ('raise AttributeError(""module {!r} has no attribute ""', 414)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_174/1009040091.py"", line 2, in <module>', '    num_even_year_movies = imdb.num_rows-np.num(Year_remainder)', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/numpy/__init__.py"", line 414, in __getattr__', '    raise AttributeError(""module {!r} has no attribute ""', ""AttributeError: module 'numpy' has no attribute 'num'. Did you mean: 'sum'?""]"
8,AttributeError,'numpy.ndarray' object has no attribute 'num',0,,2024-10-09 14:06:29.154956,"[('num_even_year_movies = imdb.num_rows-Year_remainder.num()', 2)]","['Traceback (most recent call last):', '  File ""/home/luohan/anaconda3/envs/data8/lib/python3.10/site-packages/IPython/core/interactiveshell.py"", line 3577, in run_code', '    exec(code_obj, self.user_global_ns, self.user_ns)', '  File ""/tmp/ipykernel_174/934079078.py"", line 2, in <module>', '    num_even_year_movies = imdb.num_rows-Year_remainder.num()', ""AttributeError: 'numpy.ndarray' object has no attribute 'num'. Did you mean: 'sum'?""]"
